index:
    path: /
    controller: App\Controller\DefaultController

api_get_material:
    path: /api/material
    controller: App\Controller\MaterialListController
    methods: GET

api_get_jednostka:
    path: /api/jednostka
    controller: App\Controller\JednostkaListController
    methods: GET

api_create_jednostka:
    path: /api/jednostka
    controller: App\Controller\JednostkaCreateController
    methods: POST

api_list_transactions:
    path: /api/transaction
    controller: App\Controller\TransactionListController
    methods: GET

api_edit_transactions:
    path: /api/transaction/{id}
    controller: App\Controller\TransactionEditController
    methods: PUT

api_delete_transactions:
    path: /api/transaction/{id}
    controller: App\Controller\TransactionDeleteController
    methods: DELETE
