index:
    path: /
    controller: App\Controller\DefaultController

api_list_material:
    path: /api/material
    controller: App\Controller\MaterialListController
    methods: GET

api_list_jednostka:
    path: /api/jednostka
    controller: App\Controller\JednostkaListController
    methods: GET

api_create_jednostka:
    path: /api/jednostka
    controller: App\Controller\JednostkaCreateController
    methods: POST

api_edit_jednostka:
    path: /api/jednostka/{id}
    controller: App\Controller\JednostkaEditController
    methods: PUT

api_delete_jednostka:
    path: /api/jednostka/{id}
    controller: App\Controller\JednostkaDeleteController
    methods: DELETE
